---
---
- name: Ensure git is installed
  package:
    name: "git"
    state: present

- name: Create git user
  user:
    name: "{{ git_user }}"
    generate_ssh_key: true
    state: present
    comment: "Git Server User"
    shell: "{{ git_shell }}"
    password: "{{ git_user_password }}"
    home: "{{ git_dir }}"

- name: Add authorized_keys to git user
  authorized_key:
    user: "{{ git_user }}"
    key: "{{ git_keys | join('\n') }}"
    exclusive: true
  when: git_keys | length >= 1

- name: "Clone {{ git_repo }}"
  become: yes
  become_user: git
  command:
    cmd: "git clone {{ git_repo }}"
    chdir: "{{ git_dir }}"
    creates: "{{ git_dir }}/{{ git_repo | basename | splitext | first }}/config"
  loop: "{{ git_repos }}"
  loop_control:
    loop_var: git_repo
