---
- name: Ensure git is installed
  become: true
  package:
    name: "git"
    state: present

- name: Create git user
  become: true
  user:
    name: "{{ git_user }}"
    generate_ssh_key: true
    state: present
    comment: "Git Server User"
    shell: "{{ git_shell }}"
    password: "{{ git_user_password }}"
    home: "{{ git_dir }}"

- name: Add authorized_keys to git user
  become: true
  authorized_key:
    user: "{{ git_user }}"
    key: "{{ git_keys | join('\n') }}"
    exclusive: true
  when: git_keys | length >= 1

- name: "Clone GIT Repos"
  become: true
  become_user: git
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ git_dir }}/{{ git_repo | basename | splitext | first }}.git"
  loop: "{{ git_repos }}"
  loop_control:
    loop_var: git_repo
